# 常用指令解读

## $on

位置： instance/events.js

```javascript
export function eventsMixin (Vue: Class<Component>) {
  const hookRE = /^hook:/
  Vue.prototype.$on = function (event: string | Array<string>, fn: Function): Component {
    const vm: Component = this
    if (Array.isArray(event)) {
      for (let i = 0, l = event.length; i < l; i++) {
        vm.$on(event[i], fn)
      }
    } else {
      (vm._events[event] || (vm._events[event] = [])).push(fn)
      // optimize hook:event cost by using a boolean flag marked at registration
      // instead of a hash lookup
      if (hookRE.test(event)) {
        vm._hasHookEvent = true
      }
    }
    return vm
  }
  ....
}
```

$on 函数支持单个事件注册，及多个事件注册`多个事件对应同一个处理函数`。

$on 命令会首先检查`_events`中是否有该事件， 如果没有，则声明一个空数组，把我们要监听的事件放入到该事件对应的事件数组当中。 这里并不会检测是否有重复的事件名。 因此这也是为什么当我们没有销毁之前的监听事件时，再次注册事件后，触发的时候会重复触发的其中一个原因。

## $once

位置：instance/events.js

```javascript
export function eventsMixin (Vue: Class<Component>) {
  
  ....
   Vue.prototype.$once = function (event: string, fn: Function): Component {
    const vm: Component = this
    function on () {
      vm.$off(event, on)
      fn.apply(vm, arguments)
    }
    on.fn = fn
    vm.$on(event, on)
    return vm
  }
  ....
}
```

$once的本质其实也是$on事件，但是这里将对应的事件用一个`on`事件包裹起来，在触发`on` 事件之后，就销毁掉。相当于是自动帮我们在调用之后销毁了该监听。

## $off

位置： instance/events.js

```javascript
export function eventsMixin (Vue: Class<Component>) {
  
  ....
   Vue.prototype.$off = function (event?: string | Array<string>, fn?: Function): Component {
    const vm: Component = this
    // all
    if (!arguments.length) {
      vm._events = Object.create(null)
      return vm
    }
    // array of events
    if (Array.isArray(event)) {
      for (let i = 0, l = event.length; i < l; i++) {
        vm.$off(event[i], fn)
      }
      return vm
    }
    // specific event
    const cbs = vm._events[event]
    if (!cbs) {
      return vm
    }
    if (!fn) {
      vm._events[event] = null
      return vm
    }
    // specific handler
    let cb
    let i = cbs.length
    while (i--) {
      cb = cbs[i]
      if (cb === fn || cb.fn === fn) {
        cbs.splice(i, 1)
        break
      }
    }
    return vm
  }
  ....
}
```

 `$on`是不做检查，将监听事件放入 `_events`中事件对应的数组当中，`$off`则根据传参的不同，有不同的注销方式。如果不传，则会移除所有监听事件。，如果只传入事件名，是将整个` _events`中该事件数组置换为 `null`。如果传入了事件名和对应函数，则会在 该事件数组中遍历，移除这个`fn`。  当然 `$off`也支持数组注销。

正如文档所说

```
如果没有提供参数，则移除所有的事件监听器；

如果只提供了事件，则移除该事件所有的监听器；

如果同时提供了事件与回调，则只移除这个回调的监听器。
```

## $emit

位置： instacne/events.js

```javascript
export function eventsMixin (Vue: Class<Component>) {
  
  ....
  Vue.prototype.$emit = function (event: string): Component {
    const vm: Component = this
    if (process.env.NODE_ENV !== 'production') {
      const lowerCaseEvent = event.toLowerCase()
      if (lowerCaseEvent !== event && vm._events[lowerCaseEvent]) {
        tip(
          `Event "${lowerCaseEvent}" is emitted in component ` +
          `${formatComponentName(vm)} but the handler is registered for "${event}". ` +
          `Note that HTML attributes are case-insensitive and you cannot use ` +
          `v-on to listen to camelCase events when using in-DOM templates. ` +
          `You should probably use "${hyphenate(event)}" instead of "${event}".`
        )
      }
    }
    let cbs = vm._events[event]
    if (cbs) {
      cbs = cbs.length > 1 ? toArray(cbs) : cbs
      const args = toArray(arguments, 1)
      const info = `event handler for "${event}"`
      for (let i = 0, l = cbs.length; i < l; i++) {
        invokeWithErrorHandling(cbs[i], vm, args, vm, info)
      }
    }
    return vm
  }
  ....
}
```

`$emit`会触发在 `_events`中该事件数组所有的事件。通过调用 `invokeWithErrorHandling`函数

### invokeErrorHanding

位置：util/error.js

功能： 一个 try catch 函数 触发 对应的事件，并返回结果或者错误

```javascript
export function invokeWithErrorHandling (
  handler: Function,
  context: any,
  args: null | any[],
  vm: any,
  info: string
) {
  let res
  try {
    res = args ? handler.apply(context, args) : handler.call(context)
    if (res && !res._isVue && isPromise(res) && !res._handled) {
      res.catch(e => handleError(e, vm, info + ` (Promise/async)`))
      // issue #9511
      // avoid catch triggering multiple times when nested calls
      res._handled = true
    }
  } catch (e) {
    handleError(e, vm, info)
  }
  return res
}
```

